import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';
import { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'streamie',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} p-2 w-full h-full relative`}>
                <nav className="flex justify-end gap-4 absolute top-0 right-0 py-2 px-4 z-0">
                    <Link href="/">Home</Link>
                    <Link href="/dashboard">Tmdb Dashboard</Link>
                </nav>
                {children}
            </body>
        </html>
    );
}
